name: Replace Google Meta Tag

on:
  push:
    branches:
      - main  # This triggers the workflow when you push to the 'main' branch

jobs:
  update-meta-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace form trigger on index.html
        run: |
          sed -i 's|<form class="mt-8 max-w-lg mx-auto" action="form_code" method="POST" id="contact-form" enctype="multipart/form-data">|<form class="mt-8 max-w-lg mx-auto" action="${{ secrets.FORM_KEY}}" method="POST" id="contact-form" enctype="multipart/form-data">|' index.html
