name: Replace Google Meta Tag

on:
  push:
    branches:
      - main  # This triggers the workflow when you push to the 'main' branch

jobs:
  update-meta-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace Google Site Verification meta tag
        run: |
          sed -i 's/<meta name="google-site-verification" content="meta_code" \/>/<meta name="google-site-verification" content="${{ secrets.MY_SECRET_METAKEY }}" \/>/' index.html

